site_name: scoreboard
site_description: Simple soreboard app.
repo_url: https://github.com/k-suler/scoreboard
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/k-suler">k-suler</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
